platform :ios, '9.0'
use_frameworks!

project '/Users/kseniyaborokhovskaya/Developer/FitApp/FitApp.xcodeproj'
target 'FitApp' do
pod 'RealmSwift', '~>2.6.2'
pod 'SwiftyJSON', '~>3.0'
pod 'JTAppleCalendar', '6.0'
end
